
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings

title: Eita! Magazine
email: eitamagazinebr@gmail.com
description: >- 
  Brazilian science fiction & fantasy magazine in English.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EitaMagSFF
instagram_username: eitamagsff
facebook_username: eitamagazine
mailchimp_url: newsletter


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag



# Google Analytics
google_analytics: UA-98488692-4

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
